### ISSUE TITLE
[FR] Disable not supported content in library

### ISSUE THREAD

**Issue by ecker00** [GrakovNe/lissen-android#77]
Quite a lot of content in my AudioBookShelf library are just epub and other ebook formats, not just audio books (AudioBookShelf is very versitile). When browsing it would be nice if there was a filter option on the three dots top right, to only list entries with audio book files.

**Comment by GrakovNe** [comment]
Hi!

Nothing except audiobook shall be available in the future

Confirmed as a bug

**Comment by GrakovNe** [comment]
Done in https://github.com/GrakovNe/lissen-android/releases/tag/1.1.19

How, any book/podcast without at least one [audio] chapter has been hidding from the search and library

Lissen couldn't handle e-books neither now nor in the future, so shall we show it?

**Comment by ecker00** [comment]
This change have hidden all items on my setup except for one audio book. I've been trying to identify what makes that title different from my other audio books, but I see no logic too it so far.

Looking at your commit I see you filter on `it.media.numAudioFiles`, and after some digging I understand that this is supposed to be part of the AudioBookShelf API. I updated my instance to the latest version but it did not help.

I started to manually probe the API with curl, and no idea why the field is missing on some titles for me. **Could we use another similar field as filter, like check length of `audioFiles` array can solve this? Bellow is my API response to a title that does not appear, and you can see it identifies plenty of audio tracks.** 

It could be a bug in the AudioBookShelf API, but I don't immediately see the issue there or if it's by design. https://github.com/search?q=repo%3Aadvplyr%2Faudiobookshelf%20numAudioFiles&type=code

P.S.: Also the "currently listening" view on top still show regular books when in progress, this view is not filtered (not very important).

```
{
  "id": "d01316cf-f90d-4343-98af-2b6a3c300119",
  "ino": "111838069",
  "oldLibraryItemId": null,
  "libraryId": "52e6fe7d-7c7c-4610-97e3-fbdc7d11bded",
  "folderId": "52d6298c-5823-479f-81a2-62f7fad1aff1",
  "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention",
  "relPath": "Johann Hari/Stolen Focus- Why You Can't Pay Attention",
  "isFile": false,
  "mtimeMs": 1731360168827,
  "ctimeMs": 1731360168827,
  "birthtimeMs": 0,
  "addedAt": 1731360192492,
  "updatedAt": 1733169069833,
  "lastScan": 1733169069833,
  "scanVersion": "2.7.2",
  "isMissing": false,
  "isInvalid": false,
  "mediaType": "book",
  "media": {
    "id": "6d0ecefb-0cb1-47f4-8a67-c88a1daf7e8f",
    "libraryItemId": "d01316cf-f90d-4343-98af-2b6a3c300119",
    "metadata": {
      "title": "Stolen Focus: Why You Can't Pay Attention",
      "subtitle": null,
      "authors": [
        {
          "id": "507dde62-27d9-4bac-92d3-e8a5697d2a56",
          "name": "Johann Hari"
        }
      ],
      "narrators": [
        "Johann Hari"
      ],
      "series": [],
      "genres": [
        "Audiobook"
      ],
      "publishedYear": "2022",
      "publishedDate": null,
      "publisher": "Bloomsbury Publishing Plc",
      "description": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
      "isbn": null,
      "asin": null,
      "language": null,
      "explicit": false,
      "abridged": false
    },
    "coverPath": "/metadata/items/d01316cf-f90d-4343-98af-2b6a3c300119/cover.jpg",
    "tags": [],
    "audioFiles": [
      {
        "index": 1,
        "ino": "111838074",
        "metadata": {
          "filename": "01 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/01 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "01 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 247805,
          "mtimeMs": 1731359978954,
          "ctimeMs": 1731360163599,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192456,
        "updatedAt": 1731360192456,
        "trackNumFromMeta": 1,
        "discNumFromMeta": null,
        "trackNumFromFilename": 1,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 12.434286,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "1/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 2,
        "ino": "111838072",
        "metadata": {
          "filename": "02 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/02 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "02 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 31848027,
          "mtimeMs": 1731359978970,
          "ctimeMs": 1731360163375,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192456,
        "updatedAt": 1731360192456,
        "trackNumFromMeta": 2,
        "discNumFromMeta": null,
        "trackNumFromFilename": 2,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1987.448163,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "2/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 3,
        "ino": "111838090",
        "metadata": {
          "filename": "03 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/03 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "03 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 56721196,
          "mtimeMs": 1731359978998,
          "ctimeMs": 1731360166307,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192456,
        "updatedAt": 1731360192456,
        "trackNumFromMeta": 3,
        "discNumFromMeta": null,
        "trackNumFromFilename": 3,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 3542.021224,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "3/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 4,
        "ino": "111838088",
        "metadata": {
          "filename": "04 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/04 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "04 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 36056876,
          "mtimeMs": 1731359979038,
          "ctimeMs": 1731360165971,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192456,
        "updatedAt": 1731360192456,
        "trackNumFromMeta": 4,
        "discNumFromMeta": null,
        "trackNumFromFilename": 4,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2250.501224,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "4/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 5,
        "ino": "111838080",
        "metadata": {
          "filename": "05 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/05 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "05 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 32483325,
          "mtimeMs": 1731359979074,
          "ctimeMs": 1731360164363,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192455,
        "updatedAt": 1731360192455,
        "trackNumFromMeta": 5,
        "discNumFromMeta": null,
        "trackNumFromFilename": 5,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2027.154286,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "5/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 6,
        "ino": "111838078",
        "metadata": {
          "filename": "06 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/06 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "06 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 24977196,
          "mtimeMs": 1731359979098,
          "ctimeMs": 1731360163951,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192455,
        "updatedAt": 1731360192455,
        "trackNumFromMeta": 6,
        "discNumFromMeta": null,
        "trackNumFromFilename": 6,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1558.021224,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "6/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 7,
        "ino": "111838079",
        "metadata": {
          "filename": "07 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/07 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "07 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 28604246,
          "mtimeMs": 1731359979118,
          "ctimeMs": 1731360164127,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192455,
        "updatedAt": 1731360192455,
        "trackNumFromMeta": 7,
        "discNumFromMeta": null,
        "trackNumFromFilename": 7,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1784.711837,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "7/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 8,
        "ino": "111838086",
        "metadata": {
          "filename": "08 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/08 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "08 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 39580272,
          "mtimeMs": 1731359979134,
          "ctimeMs": 1731360165707,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192455,
        "updatedAt": 1731360192455,
        "trackNumFromMeta": 8,
        "discNumFromMeta": null,
        "trackNumFromFilename": 8,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2470.713469,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "8/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 9,
        "ino": "111838083",
        "metadata": {
          "filename": "09 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/09 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "09 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 39104217,
          "mtimeMs": 1731359979154,
          "ctimeMs": 1731360165127,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192454,
        "updatedAt": 1731360192454,
        "trackNumFromMeta": 9,
        "discNumFromMeta": null,
        "trackNumFromFilename": 9,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2440.96,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "9/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 10,
        "ino": "111838084",
        "metadata": {
          "filename": "10 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/10 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "10 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 27062814,
          "mtimeMs": 1731359979178,
          "ctimeMs": 1731360165295,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192454,
        "updatedAt": 1731360192454,
        "trackNumFromMeta": 10,
        "discNumFromMeta": null,
        "trackNumFromFilename": 10,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1688.372245,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "10/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 11,
        "ino": "111838085",
        "metadata": {
          "filename": "11 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/11 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "11 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 31497361,
          "mtimeMs": 1731359979206,
          "ctimeMs": 1731360165483,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192457,
        "updatedAt": 1731360192457,
        "trackNumFromMeta": 11,
        "discNumFromMeta": null,
        "trackNumFromFilename": 11,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1965.531429,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "11/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 12,
        "ino": "111838075",
        "metadata": {
          "filename": "12 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/12 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "12 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 27725698,
          "mtimeMs": 1731359979226,
          "ctimeMs": 1731360163763,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192463,
        "updatedAt": 1731360192463,
        "trackNumFromMeta": 12,
        "discNumFromMeta": null,
        "trackNumFromFilename": 12,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1729.802449,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "12/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 13,
        "ino": "111838071",
        "metadata": {
          "filename": "13 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/13 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "13 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 22543840,
          "mtimeMs": 1731359979246,
          "ctimeMs": 1731360163191,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192464,
        "updatedAt": 1731360192464,
        "trackNumFromMeta": 13,
        "discNumFromMeta": null,
        "trackNumFromFilename": 13,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 1405.936327,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "13/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 14,
        "ino": "111838073",
        "metadata": {
          "filename": "14 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/14 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "14 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 36359063,
          "mtimeMs": 1731359979270,
          "ctimeMs": 1731360163583,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192468,
        "updatedAt": 1731360192468,
        "trackNumFromMeta": 14,
        "discNumFromMeta": null,
        "trackNumFromFilename": 14,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2269.387755,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "14/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 15,
        "ino": "111838081",
        "metadata": {
          "filename": "15 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/15 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "15 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 50557554,
          "mtimeMs": 1731359979298,
          "ctimeMs": 1731360164655,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192475,
        "updatedAt": 1731360192475,
        "trackNumFromMeta": 15,
        "discNumFromMeta": null,
        "trackNumFromFilename": 15,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 3156.793469,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "15/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 16,
        "ino": "111838070",
        "metadata": {
          "filename": "16 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/16 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "16 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 54010315,
          "mtimeMs": 1731359979338,
          "ctimeMs": 1731360163055,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192478,
        "updatedAt": 1731360192478,
        "trackNumFromMeta": 16,
        "discNumFromMeta": null,
        "trackNumFromFilename": 16,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 3372.59102,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "16/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 17,
        "ino": "111838082",
        "metadata": {
          "filename": "17 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/17 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "17 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 42900960,
          "mtimeMs": 1731359979370,
          "ctimeMs": 1731360164899,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192483,
        "updatedAt": 1731360192483,
        "trackNumFromMeta": 17,
        "discNumFromMeta": null,
        "trackNumFromFilename": 17,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 2678.256327,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "17/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 18,
        "ino": "111838087",
        "metadata": {
          "filename": "18 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/18 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "18 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 6259314,
          "mtimeMs": 1731359979390,
          "ctimeMs": 1731360165759,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192486,
        "updatedAt": 1731360192486,
        "trackNumFromMeta": 18,
        "discNumFromMeta": null,
        "trackNumFromFilename": 18,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 388.153469,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "18/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      },
      {
        "index": 19,
        "ino": "111838089",
        "metadata": {
          "filename": "19 - Stolen Focus Why You Can't Pay Attention.mp3",
          "ext": ".mp3",
          "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/19 - Stolen Focus Why You Can't Pay Attention.mp3",
          "relPath": "19 - Stolen Focus Why You Can't Pay Attention.mp3",
          "size": 492731,
          "mtimeMs": 1731359979394,
          "ctimeMs": 1731360165991,
          "birthtimeMs": 0
        },
        "addedAt": 1731360192490,
        "updatedAt": 1731360192490,
        "trackNumFromMeta": 19,
        "discNumFromMeta": null,
        "trackNumFromFilename": 19,
        "discNumFromFilename": null,
        "manuallyVerified": false,
        "exclude": false,
        "error": null,
        "format": "MP2/3 (MPEG audio layer 2/3)",
        "duration": 27.742041,
        "bitRate": 128000,
        "language": null,
        "codec": "mp3",
        "timeBase": "1/14112000",
        "channels": 1,
        "channelLayout": "mono",
        "chapters": [],
        "embeddedCoverArt": "mjpeg",
        "metaTags": {
          "tagAlbum": "Stolen Focus: Why You Can't Pay Attention",
          "tagArtist": "Johann Hari",
          "tagGenre": "Audiobook",
          "tagTitle": "Stolen Focus: Why You Can't Pay Attention",
          "tagTrack": "19/19",
          "tagDate": "2022",
          "tagComposer": "Johann Hari",
          "tagPublisher": "Bloomsbury Publishing Plc",
          "tagComment": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "tagEncoder": "LAME 32bits version 3.99.5 (http://lame.sf.net)"
        },
        "mimeType": "audio/mpeg"
      }
    ],
    "chapters": [
      {
        "id": 0,
        "start": 0,
        "end": 12.434286,
        "title": "01 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 1,
        "start": 12.434286,
        "end": 1999.882449,
        "title": "02 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 2,
        "start": 1999.882449,
        "end": 5541.903673,
        "title": "03 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 3,
        "start": 5541.903673,
        "end": 7792.404897,
        "title": "04 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 4,
        "start": 7792.404897,
        "end": 9819.559183000001,
        "title": "05 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 5,
        "start": 9819.559183000001,
        "end": 11377.580407000001,
        "title": "06 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 6,
        "start": 11377.580407000001,
        "end": 13162.292244000002,
        "title": "07 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 7,
        "start": 13162.292244000002,
        "end": 15633.005713000002,
        "title": "08 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 8,
        "start": 15633.005713000002,
        "end": 18073.965713,
        "title": "09 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 9,
        "start": 18073.965713,
        "end": 19762.337958,
        "title": "10 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 10,
        "start": 19762.337958,
        "end": 21727.869387,
        "title": "11 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 11,
        "start": 21727.869387,
        "end": 23457.671835999998,
        "title": "12 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 12,
        "start": 23457.671835999998,
        "end": 24863.608162999997,
        "title": "13 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 13,
        "start": 24863.608162999997,
        "end": 27132.995917999997,
        "title": "14 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 14,
        "start": 27132.995917999997,
        "end": 30289.789386999997,
        "title": "15 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 15,
        "start": 30289.789386999997,
        "end": 33662.380407,
        "title": "16 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 16,
        "start": 33662.380407,
        "end": 36340.636734,
        "title": "17 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 17,
        "start": 36340.636734,
        "end": 36728.790203,
        "title": "18 - Stolen Focus Why You Can't Pay Attention"
      },
      {
        "id": 18,
        "start": 36728.790203,
        "end": 36756.532243999995,
        "title": "19 - Stolen Focus Why You Can't Pay Attention"
      }
    ],
    "ebookFile": null
  },
  "libraryFiles": [
    {
      "ino": "111838074",
      "metadata": {
        "filename": "01 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/01 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "01 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 247805,
        "mtimeMs": 1731359978954,
        "ctimeMs": 1731360163599,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838072",
      "metadata": {
        "filename": "02 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/02 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "02 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 31848027,
        "mtimeMs": 1731359978970,
        "ctimeMs": 1731360163375,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838090",
      "metadata": {
        "filename": "03 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/03 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "03 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 56721196,
        "mtimeMs": 1731359978998,
        "ctimeMs": 1731360166307,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838088",
      "metadata": {
        "filename": "04 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/04 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "04 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 36056876,
        "mtimeMs": 1731359979038,
        "ctimeMs": 1731360165971,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838080",
      "metadata": {
        "filename": "05 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/05 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "05 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 32483325,
        "mtimeMs": 1731359979074,
        "ctimeMs": 1731360164363,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838078",
      "metadata": {
        "filename": "06 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/06 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "06 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 24977196,
        "mtimeMs": 1731359979098,
        "ctimeMs": 1731360163951,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838079",
      "metadata": {
        "filename": "07 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/07 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "07 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 28604246,
        "mtimeMs": 1731359979118,
        "ctimeMs": 1731360164127,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838086",
      "metadata": {
        "filename": "08 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/08 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "08 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 39580272,
        "mtimeMs": 1731359979134,
        "ctimeMs": 1731360165707,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838083",
      "metadata": {
        "filename": "09 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/09 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "09 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 39104217,
        "mtimeMs": 1731359979154,
        "ctimeMs": 1731360165127,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838084",
      "metadata": {
        "filename": "10 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/10 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "10 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 27062814,
        "mtimeMs": 1731359979178,
        "ctimeMs": 1731360165295,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838085",
      "metadata": {
        "filename": "11 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/11 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "11 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 31497361,
        "mtimeMs": 1731359979206,
        "ctimeMs": 1731360165483,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838075",
      "metadata": {
        "filename": "12 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/12 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "12 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 27725698,
        "mtimeMs": 1731359979226,
        "ctimeMs": 1731360163763,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838071",
      "metadata": {
        "filename": "13 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/13 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "13 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 22543840,
        "mtimeMs": 1731359979246,
        "ctimeMs": 1731360163191,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838073",
      "metadata": {
        "filename": "14 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/14 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "14 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 36359063,
        "mtimeMs": 1731359979270,
        "ctimeMs": 1731360163583,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838081",
      "metadata": {
        "filename": "15 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/15 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "15 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 50557554,
        "mtimeMs": 1731359979298,
        "ctimeMs": 1731360164655,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838070",
      "metadata": {
        "filename": "16 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/16 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "16 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 54010315,
        "mtimeMs": 1731359979338,
        "ctimeMs": 1731360163055,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838082",
      "metadata": {
        "filename": "17 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/17 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "17 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 42900960,
        "mtimeMs": 1731359979370,
        "ctimeMs": 1731360164899,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838087",
      "metadata": {
        "filename": "18 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/18 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "18 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 6259314,
        "mtimeMs": 1731359979390,
        "ctimeMs": 1731360165759,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838089",
      "metadata": {
        "filename": "19 - Stolen Focus Why You Can't Pay Attention.mp3",
        "ext": ".mp3",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/19 - Stolen Focus Why You Can't Pay Attention.mp3",
        "relPath": "19 - Stolen Focus Why You Can't Pay Attention.mp3",
        "size": 492731,
        "mtimeMs": 1731359979394,
        "ctimeMs": 1731360165991,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "audio"
    },
    {
      "ino": "111838076",
      "metadata": {
        "filename": "Stolen Focus Why You Can't Pay Attention.jpg",
        "ext": ".jpg",
        "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention/Stolen Focus Why You Can't Pay Attention.jpg",
        "relPath": "Stolen Focus Why You Can't Pay Attention.jpg",
        "size": 45655,
        "mtimeMs": 1731359979398,
        "ctimeMs": 1731360163779,
        "birthtimeMs": 0
      },
      "isSupplementary": null,
      "addedAt": 1731360186148,
      "updatedAt": 1733169069833,
      "fileType": "image"
    }
  ]
}
```

**Comment by GrakovNe** [comment]
Thanks for the report

numAudioFiles shall be required part of API according to https://api.audiobookshelf.org/#book API docs.

but i see that's no field in your response. Could you provide the requests also that you did to servers? That's because numAudioFiles is mandatory field in minified response, but seems like you got extended ones

i tried hotfixed the latest release: https://github.com/GrakovNe/lissen-android/releases/tag/1.1.22

it'll hide the only items which explicitly **has** zero items. If this field is ommited, the podcast or book shall be shown

**Comment by ecker00** [comment]
That change did not solve it for me unfortunately. Seems I used the wrong API endpoint, this was my request for the above response:

```
curl "http://localhost:13378/api/items/d01316cf-f90d-4343-98af-2b6a3c300119" \
  -H "Authorization: Bearer xxx"
```

I now see that it needs to be the "minified" library items according to the docs, so tried again with this:

```
curl "http://localhost:13378/api/libraries/52e6fe7d-7c7c-4610-97e3-fbdc7d11bded/items?sort=media.metadata.title&filter=authors.NTA3ZGRlNjItMjdkOS00YmFjLTkyZDMtZThhNTY5N2QyYTU2&collapseseries=1" \
  -H "Authorization: Bearer xxx"
```

And now it does indeed return `numAudioFiles` like expected:

```
{
  "results": [
    {
      "id": "d01316cf-f90d-4343-98af-2b6a3c300119",
      "ino": "111838069",
      "oldLibraryItemId": null,
      "libraryId": "52e6fe7d-7c7c-4610-97e3-fbdc7d11bded",
      "folderId": "52d6298c-5823-479f-81a2-62f7fad1aff1",
      "path": "/books/Johann Hari/Stolen Focus- Why You Can't Pay Attention",
      "relPath": "Johann Hari/Stolen Focus- Why You Can't Pay Attention",
      "isFile": false,
      "mtimeMs": 1731360168827,
      "ctimeMs": 1731360168827,
      "birthtimeMs": 0,
      "addedAt": 1731360192492,
      "updatedAt": 1733169069833,
      "isMissing": false,
      "isInvalid": false,
      "mediaType": "book",
      "media": {
        "id": "6d0ecefb-0cb1-47f4-8a67-c88a1daf7e8f",
        "metadata": {
          "title": "Stolen Focus: Why You Can't Pay Attention",
          "titleIgnorePrefix": "Stolen Focus: Why You Can't Pay Attention",
          "subtitle": null,
          "authorName": "Johann Hari",
          "authorNameLF": "Hari, Johann",
          "narratorName": "Johann Hari",
          "seriesName": "",
          "genres": [
            "Audiobook"
          ],
          "publishedYear": "2022",
          "publishedDate": null,
          "publisher": "Bloomsbury Publishing Plc",
          "description": "Why have we lost our ability to focus? What are the causes? And, most importantly, how do we get it back? For Stolen Focus, internationally best-selling author Johann Hari went on a three-year journey to uncover the reasons why our teenagers now focus on one task for only 65 seconds, and why office workers on average manage only three minutes. He interviewed the leading experts in the world on attention and learned that everything we think about this subject is wrong.",
          "isbn": null,
          "asin": null,
          "language": null,
          "explicit": false,
          "abridged": false
        },
        "coverPath": "/metadata/items/d01316cf-f90d-4343-98af-2b6a3c300119/cover.jpg",
        "tags": [],
        "numTracks": 19,
        "numAudioFiles": 19,
        "numChapters": 19,
        "duration": 36756.532243999995,
        "size": 589032810
      },
      "numFiles": 20,
      "size": 589078465
    }
  ],
  "total": 1,
  "limit": 0,
  "page": 0,
  "sortBy": "media.metadata.title",
  "sortDesc": false,
  "filterBy": "authors.NTA3ZGRlNjItMjdkOS00YmFjLTkyZDMtZThhNTY5N2QyYTU2",
  "mediaType": "book",
  "minified": false,
  "collapseseries": true,
  "include": "",
  "offset": 0
}%
```

So I'm a bit at a loss why my library would only show 1 item now. It's quite a large collection (1210 items), maybe some kind of memory issue with the filtering or so?

![IMG_20241222_230043](https://github.com/user-attachments/assets/a1de3733-b489-4b44-8e7a-6d1c14d32559)

Here is a screenshot (Big Magic is not an audio book).

**Comment by GrakovNe** [comment]
Seems like we have to research it deeply

Could you try out this release: https://github.com/GrakovNe/lissen-android/releases/tag/1.1.28

I have completely reverted the changes about numTracks field and logic around it

If it works, i have to re-think how to hide non-audio books from the list

If not - well, i'd like to connect your server for a short time to inspect what really happens here

**Comment by ecker00** [comment]
This works, shows all entries in the library. 👍 Could it be pagination? I've programmed a similar bug in the past, if you filter client side and expect X items per page but you never get to page 2 as the filtered count is less, then the offset you request to the server is incorrect.

**Comment by GrakovNe** [comment]
this is good point. I have to research to to handle these case. Sent this release to GP and other stores, thank you a ton for the bug report

**Comment by GrakovNe** [comment]
ebookFormat | String or null | The format of ebook of the book. Will be null if the book is an audiobook.
-- | -- | --

seems like the new one required field is added
